# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 00:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(upload_to='logos_cat')),
            ],
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('pagina_web', models.URLField()),
                ('logo', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='logo',
            field=models.ImageField(upload_to='logos'),
        ),
        migrations.AddField(
            model_name='startup',
            name='proveedores',
            field=models.ManyToManyField(to='proveedores.Proveedor'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='categoria_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='proveedores.Categoria'),
            preserve_default=False,
        ),
    ]
