# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 00:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_auto_20160604_0041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='categoria_id',
            new_name='categoria',
        ),
    ]
