# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0003_auto_20160604_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='latLng',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='direccion',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='latLng',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
